services:
  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: elk_es
    restart: unless-stopped
    volumes:
      - ./.docker/es01:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.17.12
    container_name: elk_kibana
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
    depends_on:
      - elasticsearch

networks:
  default:
    name: catalog_api
